name: snap_buy
description: "Snap Buy App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1
  fluttertoast: ^8.2.6
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_nav_bar: ^5.0.6
  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.0.0
  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.13.1
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/appLogoDarkFilled.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Elora
      fonts:
        - asset: assets/fonts/elora.otf
    - family: Times
      fonts:
        - asset: assets/fonts/times.ttf