// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBggJOdyqis-Uu_AYKDIYFxv4G-zkyIwU',
    appId: '1:1001866384877:web:e9c41a2143ef470ee483e4',
    messagingSenderId: '1001866384877',
    projectId: 'snap-buy-1',
    authDomain: 'snap-buy-1.firebaseapp.com',
    storageBucket: 'snap-buy-1.appspot.com',
    measurementId: 'G-CGKQE00V2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5DItDTG4GSVv3Ipz1tsv15R6A6mcFpXo',
    appId: '1:1001866384877:android:b28836c3252aaa46e483e4',
    messagingSenderId: '1001866384877',
    projectId: 'snap-buy-1',
    storageBucket: 'snap-buy-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtBDqkQezXrGV3iTWbl3o-8J87js_ujUY',
    appId: '1:1001866384877:ios:a38a1a5ab4e33e38e483e4',
    messagingSenderId: '1001866384877',
    projectId: 'snap-buy-1',
    storageBucket: 'snap-buy-1.appspot.com',
    iosBundleId: 'com.ncp.snapBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtBDqkQezXrGV3iTWbl3o-8J87js_ujUY',
    appId: '1:1001866384877:ios:a38a1a5ab4e33e38e483e4',
    messagingSenderId: '1001866384877',
    projectId: 'snap-buy-1',
    storageBucket: 'snap-buy-1.appspot.com',
    iosBundleId: 'com.ncp.snapBuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBggJOdyqis-Uu_AYKDIYFxv4G-zkyIwU',
    appId: '1:1001866384877:web:e0855917d8ea160ce483e4',
    messagingSenderId: '1001866384877',
    projectId: 'snap-buy-1',
    authDomain: 'snap-buy-1.firebaseapp.com',
    storageBucket: 'snap-buy-1.appspot.com',
    measurementId: 'G-STHQNEFPE2',
  );
}
